### ISSUE TITLE
Never sort current file as most relevant

### ISSUE THREAD

**Issue by lencioni** [wincent/command-t#107]
When I fire up Command-T, I never want to open the file that I am currently editing. I think it might be nicer to either not include it in the list of files to open, or sort it down by a notch. This often happens if I am editing a file that has a similarly named file, like a spec, and I want to go from the component to the spec or vice versa.

**Comment by UmkaDK** [comment]
Personally, I think that excluding files from the list leads to confusion: a user knows that the file exists, they type it's path/name into the search, they expect to see it on the list but it's not there. Why? "Because it is already opened" is not an obvious answer, especially if the user navigated to that file via tag jumps and thus hasn't paid much attention to the name of the file they are working in.

Changing the ranking of files based on what the user has opened leads to inconsistent order of items on the list, which doesn't seem to be ideal either.

Maybe the best approach here is to anticipate the user's action and preselect the first *unopened* file with the highest ranking. If all files on the list are already opened then preselect the first file with the highest ranking which is not shown in the current buffer. And only then, fall back to selecting a file with the highest ranking.

This way, the list of files will remain consistent every time the user opens it, yet the selector/cursor will be placed on a more likely candidate. 

It could be an optional setting which would also play nicely with #168 (which, I am not trying to promote here. It's just that the idea of preselecting an item other then the one at the top of the list was already in my head, and it seemed like a good fit here)

What do you think guys?

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
