### ISSUE TITLE
Prioritize results with the same dirname/dirpath than the file on the current buffer

### ISSUE THREAD

**Issue by seirl** [wincent/command-t#127]
When I'm editing `a/b/c/file.cc`, it would be easier to type "file" and have `a/b/c/file.hh` show up in the top of the list, instead of copying the current path every time.
I can understand that the goal is to be "path-oriented", but I think something like this would be really convenient.

**Comment by aswen** [comment]
I'm new to Command-T (come from FuzzyFinder) and miss (or can't find) [one function of FuzzyFinder](https://github.com/vim-scripts/FuzzyFinder/blob/master/doc/fuf.txt#L697) that I liked very much and it works pretty much like what @seirl requests so I add my request here rather than opening a new issue. I think this would satisfy @seirl's needs as well:
Add the option to show files in the same dir as the file that's in the currently visible buffer so only files in the same dir show up. 
It is written [here]9https://github.com/vim-scripts/FuzzyFinder/blob/master/autoload/fuf/file.vim#L44).

I would have made a PR if I knew how to build this into Command-T but I've got no idea :)

Thanks for the beautiful (it is now already) plugin anyway!

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
