### ISSUE TITLE
Error detected while processing function commandt#CommandTShowFileFinder: 

### ISSUE THREAD

**Issue by pdoak** [wincent/command-t#148]
I have just installed Command t and am getting this error when I invoke <leader>t.

Please let me know if I can give you more information.

Regards

Paul

**Comment by pdoak** [comment]
Regarding my issue, here is some further information:

System: OS X 10.10.2
MacVim: v7.4

Command t plugin installed via Pathogen.

Let me know if I can provide any further information to help.

Regards

Paul

**Comment by wincent** [comment]
Yeah, I'm going to need more info than that. What is the actual error message that you're seeing after the "Error detected" message? It should be some kind of exception.

**Comment by wincent** [comment]
See also https://github.com/wincent/command-t/issues/146, which may be the same error (not enough info to be sure).

I've pushed a commit to the `next` branch which might make it easier to collect a more useful stacktrace in this kind of situation: https://github.com/wincent/command-t/commit/888c69bce728feaa7285f6f018b2c64775e265fb

**Comment by pdoak** [comment]
wincent,

This is the exact error message when I invoke <leader>t:

Error detected while processing function commandt#CommandTShowFileFinder:
line    2:
LoadError: cannot load such file -- command-t/ext 

Let me know what else you need re info

**Comment by wincent** [comment]
Cool. So that means the C extension wasn't built (or was incorrectly
built). Are you sure you used the same version of Ruby to build Command-T
as Vim itself links against?

Can you try doing a 'make clean' and then redo the 'ruby extconf.rb &&
make' process? (Copy the output too on case we need to troubleshoot
further.)

See also the installation and troubleshooting sections in the docs; there's
a lot of info in there.

**Comment by pdoak** [comment]
Thanks for the reply.

This is what I get when I run ruby exgtconf.rb && make:

➜  command-t git:(master) ruby extconf.rb && make                                                             ⤬
checking for float.h... yes
checking for ruby.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for fcntl.h... yes
checking for stdint.h... yes
checking for sys/errno.h... yes
checking for sys/socket.h... yes
checking for ruby/st.h... yes
checking for st.h... yes
checking for pthread_create() in -lpthread... yes
creating Makefile
compiling ext.c
couldn't understand kern.osversion `14.1.0'
compiling match.c
couldn't understand kern.osversion `14.1.0'
compiling matcher.c
couldn't understand kern.osversion `14.1.0'
compiling watchman.c
couldn't understand kern.osversion `14.1.0'
linking shared-object ext.bundle
couldn't understand kern.osversion `14.1.0’

Do you have any idea how to get this working.

Regards

Paul

**Comment by wincent** [comment]
A bit of Googling suggests that there might be a problem with the Homebrew version of GCC on Yosemite (eg. https://github.com/sstephenson/ruby-build/issues/648). According to that page you could try a few options.

One is building after doing `export CC=/usr/bin/gcc`; ie:

```
export CC=/usr/bin/gcc
make clean
ruby extconf.rb
make
```

Another is trying to update your Homebrew install (if you're using Homebrew):

```
brew tap homebrew/dupes ; brew install homebrew/dupes/apple-gcc42; brew install apple-gcc42
```

Another page (http://stackoverflow.com/questions/26486163/gcc-4-9-1-in-os-x-yosemite-gcc-warning-couldn-t-understand-kern-osversion-1) suggests it might be a simple matter of doing:

```
xcode-select --install
```

Yet another page (http://apple.stackexchange.com/questions/151551/when-trying-to-upgrade-osxfuse-i-get-missing-developer-dir-path-message) suggests upgrading to Xcode 6.1.

Finally here's another page that tries to give a nice summary of the issues: http://www.zlu.me/gcc/ruby/yosemite/2014/08/28/yosemite-gcc-woe.html

As I can't repro this, I can't really tell you which of these approaches is going to be the solution. Let me know if you can find something that works for you.

**Comment by vimeitor** [comment]
Hello!

Coming here to say that I'm getting the same error message in Arch Linux, so this is not a Mac only issue.

**Comment by wincent** [comment]
@vimeitor: what's the output of `make clean && ruby extconf.rb && make` for you? I'd be extremely surprised if it is the same on Arch Linux as it is on Mac.

It's possible you're seeing another issue because any error thrown while trying to open the file finder is going to show the same top-level message, even if the underlying exception is different. (Of course, you may be seeing exactly the same issue, but there's not enough info to make that determination.)

**Comment by vimeitor** [comment]
@wincent I'm very sorry for making you lose your time. I guess I didn't compile it the right way, because it seems it's now working :). Sorry about that!

**Comment by vimeitor** [comment]
Even though I can now run it, if I call it in a fairly large directory, it crashes with the following error:
```
vimvim: symbol lookup errorsymbol lookup error: /home/vimeitor/.vim/plugged/command-t/ruby/command-t/ext.so: undefined symbol: rc_gc_writebarrier_unprotected_promoted
```
I guess it's something with ruby's garbage collector.

**Comment by wincent** [comment]
@vimeitor: That looks like a miscompilation to me (possibly a mismatch of Ruby version used to build Command-T with the version that Vim itself links against). Everything works fine until you create enough garbage to trigger a GC, at which point we try to jump to a function that's not there because it's not in that version of Ruby (or is named something different in that version of Ruby).

**Comment by pdoak** [comment]
Sorry for not getting back to you sooner. 

I managed to build it after doing export CC=/usr/bin/gcc.

Many Thanks

Paul

**Comment by wincent** [comment]
Great; glad to hear you got it working.

**Comment by jbremer** [comment]
I noticed this same error when installing Command-T through Vundle. Basically, it turns out, I was missing ruby support in Vim (apt-get install vim-nox) and, more importantly, the compilation of command-t failed because I didn't have a development version of ruby installed (apt-get install ruby-dev).
What's more annoying though is that Vundle didn't report any error about the failed compilation - as far as I've seen. Could this be something that could be looked into, perhaps? :)

**Comment by wincent** [comment]
Not a Vundle user myself but yes, sounds like it would be good for it to
complain loudly if the build fails. Want to open a ticket on the Vundle
issue tracker?
