### ISSUE TITLE
Highlight color changes on subsequent `:CommandT`

### ISSUE THREAD

**Issue by bezhermoso** [wincent/command-t#170]
Hi,

Here are a couple of screenshots that illustrate the issue:

<img width="1522" alt="screen shot 2015-08-29 at 11 38 30 pm" src="https://cloud.githubusercontent.com/assets/1437428/9566047/a19059e2-4ea7-11e5-8410-c5bafd322e31.png">

`g:CommandTHighlightColor = "PmenuSel"` is explicity defined in my `.vimrc`, and it is working as expected at this point.

On subsequent use of `:CommandT` however, I get this:

<img width="1522" alt="screen shot 2015-08-29 at 11 38 47 pm" src="https://cloud.githubusercontent.com/assets/1437428/9566061/6d28b9fa-4ea8-11e5-9b98-2cb273fe2d8b.png">

As you can see, the file name under the cursor is blends with the background rendering it unreadable. I confirmed that `PmenuSel` did not change, so it couldn't be this: https://github.com/wincent/command-t/issues/133

Any thoughts as to why this is happening?

**Comment by bezhermoso** [comment]
Would like to add that the `No Matches` highlight color stops working as well.

**Comment by wincent** [comment]
Thanks for the report! I haven't seen this before. I'll need to refresh my memory around this code to see if anything occurs to me that could explain why this might happen. This may generate some questions for you.

**Comment by bezhermoso** [comment]
No problem!

Here are some additional info:

I tried using different highlight color sets for it but it still happens -- seems like the foreground color changes to the background color from the second time until you quit vim. **However**, this doesn't happen when using `Visual`.

Hope that will help you drill it down in some way. :)

**Comment by wincent** [comment]
Sorry for the lack of communication on this one. Just checking in: did you ever figure it out? I am suspicious of some `:autocmd` that you may have in your set-up or in a plug-in that is causing this to happen. I'd try turning off some stuff to see if you can identify where the interaction is coming from.

Independently of whether you find the problem in your set-up and fix it, we might be able to make Command-T resilient against this by re-setting-up the color configuration each time it is opened, instead of just when it is first opened.

**Comment by wincent** [comment]
Going to close this due to inactivity but feel free to comment again if you have anything new to add and I'll re-open it.
