### ISSUE TITLE
Suggestion: make g:CommandTMatchWindowReverse default to 1

### ISSUE THREAD

**Issue by lencioni** [wincent/command-t#187]
The reverse option is great because it puts the best suggestion close to where you are typing, and it is in a fixed location. This prevents your eyes from having to bounce around as you use Command-T. In observing people who have set up Command-T, I found that most just use the default order, which unnecessarily slows them down while working. I think that due to its better ergonomics and the low likelihood that people will discover and change the default that this option should be defaulted to 1. What do you think?

**Comment by wincent** [comment]
I agree that this option is an improvement (I've been using it myself ever since it was added, back in April 2011 in commit 372456775709 [[proof](https://github.com/wincent/wincent/commit/3578f2ca98aeec84113e8e3cbe3ef5afbce05223)]), and I actually thought about piling together all the potential breaking changes — including toggling this default — in one fell swoop in the 2.0 release. At least some of the Command-T [settings in my dotfiles](https://github.com/wincent/wincent/blob/e6949d9543b972ed8979a800a0d2e9e2f4dbf887/roles/dotfiles/files/.vim/after/plugin/command-t.vim#L4-L10) are, by definition, settings that I would consider to be reasonable defaults for most people.

Trouble is, though, the way the Vim plug-in ecosystem works is that most people are tracking the `master` branch at all times via a plug-in manager, and so the notion of "releases" is becoming less and less meaningful. It means that things like semver and even the very concept of "release notes" become less useful. As a result, I've always been very, very careful about preserving backwards compatibility.

At least for things like renamed or deleted functions I was able to add deprecation warnings in the 2.0 release (see commit afc9442869b8d690), but I can't really do that for options whose defaults have changed. I may just need to bite the bullet at some point and make the breaking change anyway. For some users it will cause pain, for others, enlightenment, and for others still might just be a UX improvement that goes unnoticed.

**Comment by lencioni** [comment]
> For some users it will cause pain, for others, enlightenment, and for others still might just be a UX improvement that goes unnoticed.

I believe that the number of users that this particular change will cause pain for is relatively low and the solution to the pain is relatively simple. In my mind, the benefit here definitely outweighs the downside, and the earlier you make this change, the more benefit it will have and the less pain it will cause.

**Comment by wincent** [comment]
All right, I pulled the trigger on the `next` branch.

**Comment by lencioni** [comment]
Awesome! Exciting times we live in.

**Comment by spicyj** [comment]
This surprised me today (hadn't pulled in a while…) but I figured out what changed with a bisect. :)

**Comment by lencioni** [comment]
Sorry about the surprise @spicyj! I'm curious: did you stick with the new default?

**Comment by spicyj** [comment]
I didn't, but I had a fixed height already set. Maybe one day I'll switch.
