### ISSUE TITLE
let g:CommandTMaxHeight question

### ISSUE THREAD

**Issue by haolongzhangm** [wincent/command-t#191]
>>>      The maximum height in lines the match window is allowed to expand to.
      If set to 0, the window will occupy as much of the available space as
      needed to show matching entries.
from the explain，when the  let g:CommandTMaxHeight=0
I think I can use page down to show more than one page result list,  I think I can show numbers max to 
CommandTMaxFiles

but now only show one page result

**Comment by wincent** [comment]
Thanks for the question, @haolongzhangm.

Setting the max height to zero _does not_ add the ability to scroll the results listing with page up/down or via any other means (eg. cursor up/down). All it does is to affect the displayed height of the results listing. Setting it to 0 means it will occupy up to the full vertical height of the Vim window if there are enough results to justify it.

If the result you want is not visible in the listing, then you need to add more characters to refine your search term.

I'm going to close this for now, but let me know if you have any further questions. I'd also be open to hearing any suggestions for improving the docs in order to make them less confusing; perhaps they should mention the fact that the match listing is not scrollable.
