### ISSUE TITLE
Ruby version check is draconian

### ISSUE THREAD

**Issue by voxik** [wincent/command-t#192]
There was recently updated Ruby in Fedora and command-t stopped working with error message:

```
command-t.vim could not load the C extension
Please see INSTALLATION and TROUBLE-SHOOTING in the help
Vim Ruby version: 2.2.4-p230
Expected version: 2.2.3-p173
For more information type:    :help command-t
Press ENTER or type command to continue
```

This is really to strict. The Ruby patch levels are always API/ABI compatible, so there is no reason to not continue to use the extension as it was.

Could you please relax the Ruby version checks? You should be using something like:

```
$ ruby -rrbconfig -e 'puts RbConfig::CONFIG["LIBRUBY"]'
libruby.so.2.2.0
```

**Comment by wincent** [comment]
Hi @voxik, thanks for opening the issue. I am pretty wary of loosening the check too much, although your proposed `LIBRUBY` check _may_ be an acceptable compromise.

To give you some insight into why the check is so strict: _by far_ the number one "bug" report I've gotten over the years is Vim crashing due to Command-T miscompilation (ie. a user error, but one which _looks_ to the user like a catastrophic bug in Command-T). I'd rather bias towards strictness, at the possible cost of some inconvenience (with a helpful error message), rather than have users puzzled by mysterious crashing.

Here's a sample of issues about Command-T crashing Vim. Command-T has never had a crashing bug, so all of these are explained in terms of miscompilation. Note that the actual number of reports is much higher when you include emails that I receive, and "me too" comments on these issues:

- https://github.com/wincent/command-t/issues/67
- https://github.com/wincent/command-t/issues/97
- https://github.com/wincent/command-t/issues/123
- https://github.com/wincent/command-t/issues/143
- https://github.com/wincent/command-t/issues/144
- https://github.com/wincent/command-t/issues/148
- https://github.com/wincent/command-t/issues/160
- https://github.com/wincent/command-t/issues/175
- https://wincent.com/issues/1545
- https://wincent.com/issues/1647
- https://wincent.com/issues/1691
- https://wincent.com/issues/1715
- https://wincent.com/issues/1716
- https://wincent.com/issues/1741
- https://wincent.com/issues/1781
- https://wincent.com/issues/1819
- https://wincent.com/issues/1826
- https://wincent.com/issues/2019
- https://wincent.com/issues/2054
- https://wincent.com/issues/2080
- https://wincent.com/issues/2150
- https://wincent.com/forums/command-t/topics/470

Hopefully you can see why the check is strict; I'm trying to be helpful to people who evidently are having trouble with a somewhat sensitive and brittle installation process. I'm explicitly erring on the side of strictness, not to be "draconian" but to eliminate a major source of problems.

The docs have explicitly warned people to use "the same version of Ruby to compile Command-T as Vim itself is linked against" or words to that effect since about commit 45cc254f0815824038138f2 (in [this part](https://github.com/wincent/command-t/commit/45cc254f0815824038138f2cccf5f2706ad23f49#diff-6e2ea3a1b206d3bd25176c937df9df48R124) of the docs). That advice has been in place since April 2010 yet it continued to be a constant source of support inquiries and bug reports; the number of reports has definitely gone down since this diagnostic method was introduced. I think the reason people are so prone to get this wrong is that tools like RVM, rbenv and chruby encourage them to mix and match their Ruby versions, making version conflicts much more likely.

**Comment by voxik** [comment]
Yeah, I totally understand your point. Binary compatibility is an issue not only for Command-T, but monitoring ruby-core, there is steady inflow of this kind of issues.

Nevertheless, I came to this issue exactly from the opposite direction, since I am packaging Command-T for Fedora to prevent myself and our users precisely against this issues. The packaging system ensures the binary compatibility by explicit dependencies on .so file versions (you can see the automatically generated dependency here [1]), given that upstream properly versions their libraries. So this was totally unexpected that after minor update of Ruby, the plugins stopped working without any prior notice.

So until I find time to submit PR, I'll probably tighten the dependency in vim-command-t package to ensure proper functionality. Unfortunately it still means additional work with rebuild of this package after every Ruby update :/

[1] http://koji.fedoraproject.org/koji/rpminfo?rpmID=7167571

**Comment by Garonenur** [comment]
I don't want to open a new issue for my problem, as I think it is linked to this issue. but Command-T stopped working for me, and the error message is as follows:
```
command-t.vim could not load the C extension
Please see INSTALLATION and TROUBLE-SHOOTING in the help
Vim Ruby version: 2.3.1-p112
Expected version: 2.3.0-p0
For more information type:    :help command-t
```
OK, I thought, this is funny, as I have compiled vim and Command-T at the same time and only one ruby version is installed.
ldd on the vim-binary and on ext.so (grep for ruby) returns this:
vim:
```
libruby-2.3.so.2.3 => /usr/lib/x86_64-linux-gnu/libruby-2.3.so.2.3 (0x00007f514bc6f000)
```
ext.so:
```
libruby-2.3.so.2.3 => /usr/lib/x86_64-linux-gnu/libruby-2.3.so.2.3 (0x00007fbf9ede0000)
```
so, as far as I can see, they both link to the same library, but the version check does not recognize this.
Any ideas on how to fix this?

**Comment by Garonenur** [comment]
ignore me.
I should remember to always restart vim after doing something like a recompile on any of its parts.

**Comment by joelostblom** [comment]
Hi, I am getting the same error message as @Garonenur, with the same ruby version numbers conflict. However, I have not done any manual recompiling of either vim or ruby, just installed and updated them through pacman.

I could not locate a file called `ext.so` on my system (antergos, arch-derivative), so I ran `ldd` on the ruby and vim files in `/usr/sbin/`.

For ruby, I get
```
libruby.so.2.3 => /usr/lib/libruby.so.2.3 (0x00007fdde2853000)
```
but for vim I don't see any `libruby` among the returned libraries. The fill list for vim is

```
linux-vdso.so.1 (0x00007fff68595000)
libgtk-x11-2.0.so.0 => /usr/lib/libgtk-x11-2.0.so.0 (0x00007febec0c2000)
libgdk-x11-2.0.so.0 => /usr/lib/libgdk-x11-2.0.so.0 (0x00007febebe0d000)
libgdk_pixbuf-2.0.so.0 => /usr/lib/libgdk_pixbuf-2.0.so.0 (0x00007febebbe7000)
libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x00007febeb861000)
libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0x00007febeb615000)
libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007febeb3c3000)
libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007febeb0b4000)
libSM.so.6 => /usr/lib/libSM.so.6 (0x00007febeaeac000)
libICE.so.6 => /usr/lib/libICE.so.6 (0x00007febeac8f000)
libXt.so.6 => /usr/lib/libXt.so.6 (0x00007febeaa26000)
libX11.so.6 => /usr/lib/libX11.so.6 (0x00007febea6e4000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007febea3e0000)
libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007febea173000)
libacl.so.1 => /usr/lib/libacl.so.1 (0x00007febe9f6a000)
libgpm.so.2 => /usr/lib/libgpm.so.2 (0x00007febe9d63000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007febe9b5f000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007febe9942000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007febe95a4000)
libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007febe93a0000)
libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0x00007febe9193000)
libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007febe8f8d000)
libatk-1.0.so.0 => /usr/lib/libatk-1.0.so.0 (0x00007febe8d67000)
libcairo.so.2 => /usr/lib/libcairo.so.2 (0x00007febe8a39000)
libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0x00007febe8824000)
libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007febe85e0000)
libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007febe83d6000)
libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0x00007febe81d3000)
libXi.so.6 => /usr/lib/libXi.so.6 (0x00007febe7fc3000)
libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x00007febe7db8000)
libXcursor.so.1 => /usr/lib/libXcursor.so.1 (0x00007febe7bad000)
libXcomposite.so.1 => /usr/lib/libXcomposite.so.1 (0x00007febe79aa000)
libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x00007febe77a7000)
libXext.so.6 => /usr/lib/libXext.so.6 (0x00007febe7595000)
libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007febe735f000)
libz.so.1 => /usr/lib/libz.so.1 (0x00007febe7149000)
libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007febe6f32000)
libthai.so.0 => /usr/lib/libthai.so.0 (0x00007febe6d29000)
libffi.so.6 => /usr/lib/libffi.so.6 (0x00007febe6b20000)
libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007febe68ad000)
libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007febe66a8000)
libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007febe647f000)
/lib64/ld-linux-x86-64.so.2 (0x00007febec702000)
libattr.so.1 => /usr/lib/libattr.so.1 (0x00007febe627a000)
libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007febe5fbe000)
libpixman-1.so.0 => /usr/lib/libpixman-1.so.0 (0x00007febe5d16000)
libEGL.so.1 => /usr/lib/libEGL.so.1 (0x00007febe5ae5000)
libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x00007febe58e1000)
libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x00007febe56d3000)
libGL.so.1 => /usr/lib/libGL.so.1 (0x00007febe545f000)
librt.so.1 => /usr/lib/librt.so.1 (0x00007febe5257000)
libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007febe4fdb000)
libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007febe4db1000)
libdatrie.so.1 => /usr/lib/libdatrie.so.1 (0x00007febe4ba9000)
libXau.so.6 => /usr/lib/libXau.so.6 (0x00007febe49a5000)
libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007febe479f000)
libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007febe458f000)
libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0x00007febe438d000)
libxcb-dri2.so.0 => /usr/lib/libxcb-dri2.so.0 (0x00007febe4188000)
libxcb-xfixes.so.0 => /usr/lib/libxcb-xfixes.so.0 (0x00007febe3f80000)
libxcb-dri3.so.0 => /usr/lib/libxcb-dri3.so.0 (0x00007febe3d7d000)
libxcb-present.so.0 => /usr/lib/libxcb-present.so.0 (0x00007febe3b7a000)
libxcb-sync.so.1 => /usr/lib/libxcb-sync.so.1 (0x00007febe3973000)
libxshmfence.so.1 => /usr/lib/libxshmfence.so.1 (0x00007febe3770000)
libgbm.so.1 => /usr/lib/libgbm.so.1 (0x00007febe3562000)
libwayland-client.so.0 => /usr/lib/libwayland-client.so.0 (0x00007febe3353000)
libwayland-server.so.0 => /usr/lib/libwayland-server.so.0 (0x00007febe3141000)
libdrm.so.2 => /usr/lib/libdrm.so.2 (0x00007febe2f32000)
libglapi.so.0 => /usr/lib/libglapi.so.0 (0x00007febe2d03000)
libxcb-glx.so.0 => /usr/lib/libxcb-glx.so.0 (0x00007febe2ae7000)
libXxf86vm.so.1 => /usr/lib/libXxf86vm.so.1 (0x00007febe28e1000)
libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007febe26b5000)
```

I check `/usr/sbin/vi` also, but nothing there either:
```
linux-vdso.so.1 (0x00007ffc91b70000)
libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007fee13e43000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007fee13aa5000)
/lib64/ld-linux-x86-64.so.2 (0x00007fee140b0000)
```

Sorry, I am not very familiar with how to troubleshoot this. I have not been using Commant-T for a while, so I cannot pinpoint this to a specific update, but I have been rebooting since my last update, so restarting vim does not fix this problem for me. Any idea of what I can get Command-T working again?

**Comment by wincent** [comment]
@joelostblom: Can I suggest that you open a new issue for this, as it is basically unrelated to the original issue? (This issue is about whether the check should exist and if so, how strict it should be, whereas your issue is a request for troubleshooting support.)

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
