### ISSUE TITLE
Only include certain filetypes or directories

### ISSUE THREAD

**Issue by Bothari** [wincent/command-t#223]
I am using command-t on a large project (100k+ files in the root), but I am able to significantly limit the size of the search manually by _including_ certain file types (.cpp, .h, .mk, etc), or by _including_ certain directories (of about 50 directories in the root, I only want 3-4).

I would rather not have to write a wildignore expression which explicitly ignores dozens of file types and directories, it would be considerably more efficient to just write a "wildinclude", if that makes sense.

Is there a way to currently do this, or could it be easily added to Command-T?

I was previously using Ctrl-P, and was able to hack it into their "ctrlp_custom_ignore" setting as such:

```
:let g:ctrlp_custom_ignore = {
    \ 'file': '\v(\.cpp|\.inl|\.h|\.dc|\.mk|\.py)@<!$'
    \ }
```

Ctrl-P was far too slow to use on the project though, Command-T is much more efficient.

Thanks in advance.

**Comment by wincent** [comment]
As I said on your other issue (#224), I'm currently using Command-T in a huge directory with approximately 1 million files. I've found that I can get a long way just by sprinkling some characters from the leading part of the paths, and I've never felt the need to add a complicated wildignore pattern.

For example, if the three directories you care about in the root are "foo", "bar" and "baz", prefixing your search with "foo", "bar", "baz" will help a lot. You could also end your search with a specific extension (eg. ".cpp"). If I haven't found what I am looking for by the time I have entered "foo" and "thing", adding the extension usually gets me there.

I've also heard of people making specific mappings for directories that they tend to search in; eg. you could make a mapping `<Leader>f` that does `:CommandT foo<CR>`, or alternatively you could use `feedkeys()` if you want to keep the scope at the top level of the repo. I haven't found it necessary to do that even in huge directories.

If you want to do something like your `g:ctrlp_custom_ignore` hack you should be able to do the same with `g:CommandTWildIgnore`; you just need to convert it to a Ruby regular expression instead of a VimL one.

**Comment by Bothari** [comment]
Excellent, thank you very much for the feedback. I didn't realise I would have to make `g:CommandTWildIgnore` a Ruby regexp, very good info. I'll try and setup the watchman thing this weekend.

I appreciate your hard work, Command-T is fantastic.

Max
