### ISSUE TITLE
Use command-t to insert header files.

### ISSUE THREAD

**Issue by Bothari** [wincent/command-t#230]
I've recently been refactoring a lot of code, and have needed to insert a lot of header files to existing source files. I would love it if there was a mode of command-t which would let me do that. I already find myself using command-t to search for the correct header file, and then having to manually type out the #include line (although I've now written a quick macro which will create the appropriate #include line for a given file into a buffer).

I imagine it would work something like this:

1. In insert mode, type \<leader\>i
2. A command-t buffer appears, which lets me search for files as normal.
3. Upon selecting a file, a user function is (optionally) called which can format the file name (for example making it relative instead of absolute, and adding "#include" at the start).
4. The file name (optionally munged by the user function) is then inserted at the cursor position.

Thanks!

Max

**Comment by wincent** [comment]
Sounds like this would be a good job for YouCompleteMe (which also has a fuzzy approach). Have you thought about that? I don't know what exists in the way of context-sensitive completion for your language, or if you'd have to write a custom completer (this is not too hard; I've done a hacky one for my own purposes [here](https://github.com/wincent/ycmd/commit/174a14ef9750dd089ee05613fccad961cc1a9937)).

**Comment by Bothari** [comment]
Ah, possibly. I have been toying with YCM, but integrating it with our codebase has proven really painful for various reasons. Are you suggesting I could make YCM actually hook into the CommandT database to find the correct file? That might work.

**Comment by wincent** [comment]
> Are you suggesting I could make YCM actually hook into the CommandT database to find the correct file?

No, I think it's best to use a focused tool for each specific task, so YCM for inserting text into buffers, Command-T for selecting places to jump to, and if you're working on a really large codebase, Watchman to interrogate the filesystem.

About Watchman, Command-T *does* ask it for the file list when you use `g:CommandTFileScanner='watchman'`, because it's delegating the thing that Watchman is good at to Watchman. If you're in a very large repo then you'd want YCM to talk to Watchman as well for the same reasons.
