### ISSUE TITLE
Ruby errors when trying to start CommandT with Watchman scanner

### ISSUE THREAD

**Issue by Bothari** [wincent/command-t#234]
The only relevant config value I have set up is `g:CommandTFileScanner = 'watchman'`. I have watchman running on a relevant directory:

```
(0) 16:50 > ./bin/watchman.exe watch-list
{
    "version": "3.7.0",
    "roots": [
        "C:\\perforce\\main\\shared\\src"
    ]
}
```

When I run :CommandT inside Vim, I get a bunch of Ruby error spam. I actually don't know how to copy/paste the error spam from gvim, so here's the text of the first couple of lines, and a screenshot showing the rest.

```
c:/Program Files/Vim/vimfiles/bundle/command-t/ruby/command-t/scanner/file_scanner/watchman_file_scanner.rb:22:in `load'
c:/Program Files/Vim/vimfiles/bundle/command-t/ruby/command-t/scanner/file_scanner/watchman_file_scanner.rb:22:in `paths!'
```

![commandt](https://cloud.githubusercontent.com/assets/18599875/17121460/bccc0982-5288-11e6-8db3-6a1dc60fe5b7.png)

Any advice on what might be going wrong?

**Comment by wincent** [comment]
The watchman support is probably not going to work on Windows because (my understanding is that) there is no socket support on Windows. Specifically, [this line](https://github.com/wincent/command-t/blob/354c429dad34f7d163663943c948f819588b53d3/ruby/command-t/scanner/file_scanner/watchman_file_scanner.rb#L26) is going to carp out on Windows, I expect. It's used `UNIXSocket` ever since it was first implemented in https://github.com/wincent/command-t/commit/d24139eb779131b6a2414326d9023a6e5790e6d4.

I'd be willing to accept a pull request that made it work on Windows (by optionally shelling out to the Watchman process instead of trying to communicate over a socket), but as I don't have a Windows install for testing this is not something that I've developed myself.

For now, the easiest thing may just be to not use that scanner.

**Comment by Bothari** [comment]
Ah, I suspected it would be a Windows issue. Thanks for the clarification. I'll see if I can hack together a fix, but my Ruby skills are rudimental!
