### ISSUE TITLE
errors with ruby version 2.3.1

### ISSUE THREAD

**Issue by joostliketoast** [wincent/command-t#254]
I get the following error if i install command-t with ruby version:

```
Error detected while processing /Users/joost/dotfiles/vim/bundle/command-t/autoload/commandt.vim:
line  183:
fatal: incompatible library version - /Users/joost/.vim/bundle/command-t/ruby/command-t/ext.bundle
Error detected while processing function commandt#FileFinder:
line    2:
NoMethodError: undefined method `show_file_finder' for nil:NilClass
```

**Comment by wincent** [comment]
Not sure whether the `fatal` error message is coming from Ruby or Vim but it is not coming from inside Command-T itself.

I'd blow everything away and start again (`make clean && ruby extconf.rb && make` in the Command-T directory where you did the original build, and also make sure that you don't have any duplicate/old copies of Command-T installed anywhere else).

**Comment by joostliketoast** [comment]
`rvm use system && make clean && ruby extconf.rb && make`  fixed it in general. But i switch a lot between different rails projects with different ruby versions. And depending on which project i am in get different gem errors the first time i call command-T but it works fine and doesn't show the errors afterwards. But it might be unrelated to command-T

![2__vim__vim_](https://cloud.githubusercontent.com/assets/5398047/20146404/1abeacec-a6a4-11e6-9102-1266846cb787.png)

**Comment by wincent** [comment]
Ouch. That is pretty ugly, @joostliketoast. I wonder if that is due to some directory-specific `Gemfile` or `Gemfile.lock`. If you can figure out what is printing that message I'd be more than happy to find a way to suppress it, even if it means doing some nasty monkey-patching.

**Comment by joostliketoast** [comment]
@wincent yeah it's an ugly beast for sure. I first assumed it would be related to a Gemfile too, but even if i open vim inside a directory without a Gemfile it opens like above.

**This scenario works fine:**
`rvm use system` Then start vim project folder and launch command-T no issues. 
_The system ruby is also the version with which command-t is build and which vim uses_

**This scenario doesn't work:**
go to rails or ruby project folder that uses a different version then the system ruby. rvm automatically switches because of the `.ruby-version` file. Then start vim and launch command-T and it will show the errors again.

So it seems as soon as rvm uses a different version then system ruby it gives issues. No idea why yet...

**Comment by robvolk** [comment]
Got the same error when I invoked cmd+T from vim.

`cd ~/.vim/bundle/command-t.vim/ruby/command-t && clean && ruby extconf.rb && make` fixed it.

**Comment by wincent** [comment]
I'd definitely like to be able to fix this centrally for everybody, without each person who runs into this having to figure it out for themselves, but I don't use `rvm` and I can't reproduce this.  Going to add the "help needed" label, but I'm not going to take any further action on this myself for now. Please keep me posted if you find out more.

**Comment by ecbrodie** [comment]
I can report that I am running into this issue with command-t on my Ruby projects, similar to the screenshot with the orange highlights for the `gem install` issues. I am an `rvm` user too.

**Comment by pavelz** [comment]
same here, for some reason this was not happening before.

**Comment by ecbrodie** [comment]
@wincent I would like to change your perspective on you inability to reproduce this bug because you are not an `rvm` user. I respect that you have your own way to install and maintain Ruby on your system. However, you need to recognize that `rvm` has basically become the industry standard for installing Ruby onto machines at this point. Neglecting to support this popular tool just because you do not use it will basically mean that you are unwilling to make your library available to this large chunk of the population. `rvm` should be easy enough to install that you can use it just to reproduce the defect, and then tear it down after.

**Comment by wincent** [comment]
@ecbrodie: Thanks for the input. Nevertheless, I think you're operating under some misconceptions, which I'll try to address below.

> `rvm` has basically become the industry standard for installing Ruby onto machines at this point.

This is untrue: other significant, popular alternatives include `rbenv`, `chruby` (for switching versions) and `ruby-install` (for installing versions). There may be others that I am not aware of. And of course, there are large groups who just use the system-provided Ruby or one that comes via their system's package manager, whether it be Homebrew or `rpm` or `apt-get` etc.

> Neglecting to support this popular tool just because you do not use it will basically mean that you are unwilling to make your library available to this large chunk of the population

This is incorrect on multiple levels. The question of how a user chooses to get/manage/install Ruby is orthogonal to Command-T: in this sense, I've always understood and "supported" that people use different tools to deal with Ruby. This is why the docs have provided installation and trouble-shooting tips acknowledging the diversity of approaches that people take; it is difficult, however, to put much into the code to mitigate or control circumstances that are outside of the control of Command-T (although I've done what I can, such as [this stuff](https://github.com/wincent/command-t/blob/5a19460ea0eab0ca617a8dbf405f7a506eca4ff6/autoload/commandt.vim#L158-L169)).

And what does it mean to you to "support" the tool? What do you think me answering questions on this issue tracker is, if not "support"? I'm clearly not "unwilling" to make my library unavailable: it is open source, it is free, and I have patiently helped many people work through their installation issues over the years. This is very frustrating because there have been dozens of "bug" reports like this over the years about Command-T not working in certain environments: *in every single case* it was *user error* (specifically compilation error by the user: using the wrong version, having multiple copies installed etc). I'm aware that the user errors are *mostly* enabled by Command-T being hard to install, but for reasons I'll explain below, there is not much I can (practically) do about that. An additional source of frustration is that these problems are greatly exacerbated by hacks like `rvm` and so on (yes, they *are* hacks, no matter how useful they are — and of course, they are very useful in many scenarios), but I have yet to see even a single useful argument for the need to run the bleeding edge, or the latest, or anything but the system ruby, in your editor environment; neither Command-T, nor any other editor plug-in that I know of, relies on recent Ruby features, and even the potential speed argument doesn't cut it because all the performance-critical parts of Command-T are written in C. In other words, in a sense, if you use a tool like `rvm`, you've brought all this on yourself.

> `rvm` should be easy enough to install that you can use it just to reproduce the defect, and then tear it down after.

`rvm` would certainly be easy to install but it is *not at all clear* that installing it would be enough to reproduce the defect. In fact, given that there is a small number of reports here, I think it is highly likely that only a subset of `rvm` users are seeing it, and that there are no guarantees that me installing it would put me in that subset. So, I'm relying on somebody who *can* reproduce it and who cares enough to figure out how to fix their stuff or provide me with enough information to enable me to implement a mitigation.

I recognize that Command-T is hard to install. I wish it wasn't. The difficulty is that running Ruby in-process is going to lead to a bunch of compatibility issues whenever users compile Command-T with a version of Ruby that doesn't match the version of Ruby that Vim links against. On the other hand, running Ruby in-process means we can execute fast C code, and that's one of the key reasons why Command-T is fast. And speed is *everything* to Command-T, basically its principal reason to exist at all. It is hard to have one (speed) without the other (hard installs). https://github.com/wincent/command-t/issues/220 tracks making Command-T run in a separate process — which is my attempt to "have our cake and eat it too" — but that's a huge change and it will likely be a while before it fully materializes.

My position on this is still what I said [above](https://github.com/wincent/command-t/issues/254#issuecomment-265068922):

> I'd definitely like to be able to fix this centrally for everybody, without each person who runs into this having to figure it out for themselves, but I don't use `rvm` and I can't reproduce this. Going to add the "help needed" label, but I'm not going to take any further action on this myself for now. Please keep me posted if you find out more.

**Comment by wincent** [comment]
Closing this one due to inactivity, and also because all the Ruby-related headaches should go away with the Lua rewrite (https://github.com/wincent/command-t/issues/380).
