### ISSUE TITLE
Advise Brew+Rbenv (and RVM?) users to use system Ruby

### ISSUE THREAD

**Issue by joallard** [wincent/command-t#255]
Linking to the right Ruby version has made me stumble a few times, but I think I figured out a pretty good way to do it, and I'd like to share it here, if it's good maybe it can make it into the instructions.

I installed Vim with Brew, and it loaded Ruby as a dependency. Checking what is "system Ruby", it appears to be in fact, the one installed by Brew. Vim must have been compiled with the Brew ruby.

So when I upgraded Vim, I went to the `command-t` directory, set the local version to the system one, and compiled. Voilà. No fuss, no checking "which version is Vim linked against" and manually installing and setting that version.

```
$ rbenv local system
$ cd ruby/command-t
$ ruby extconf.rb
$ make
```

\[documentation]

**Comment by wincent** [comment]
I've already tried to cover more or less this information in the docs (see [here](https://github.com/wincent/command-t/blob/d2467c84af8a1f1a2d0366127550d0a241dd2548/doc/command-t.txt#L334)). Feel free to submit a PR if you think that section (or related ones) can be improved.

**Comment by joallard** [comment]
Yep, I read that this morning. Of course. My post was more of an RFC, do you think we ought to put it in the instructions? Do you see obvious ways it could fail? That was more what I was after, but I guess nothing is obviously wrong.

**Comment by wincent** [comment]
I'm definitely open to improving the docs and even making some more suggestions. It is tricky, however, because there is a lot of into in there and quite a few nuances. Even when adding helpful information to the docs, the practical effect might not actually be an improvement because people don't even really know where to start.

So feel free to submit a PR, like I said. In the long term, the real "fix" is just going to be to make the darn thing easier to install in the first place (see #220 for more details on that one).

**Comment by joallard** [comment]
Okay!
