### ISSUE TITLE
With the watchman scanner, vim becomes unresponsive when opened in home dir

### ISSUE THREAD

**Issue by trotzig** [wincent/command-t#263]
I'm using the watchman scanner. Most of the time, it makes Command-T a lot faster, at least for large project folders. But if I open vim from the home directory and use Command-T, things freeze. 

For my project import-js, which also uses watchman, I ended up disabling watching files from the home dir: 
https://github.com/Galooshi/import-js/commit/354b9b114f1adea862f6cdd17dfb33fd8cd8609c

Have you thought about this? Are there other solutions?

**Comment by wincent** [comment]
Yeah, so this most likely happens because:

* You have Watchman set up with `root_restrict_files`/`root_files` ([docs](https://facebook.github.io/watchman/docs/config.html)) to not work on non-repo dirs (and your `$HOME` happens to not be a repo), which means that it falls back to the `find`-based scanner, which can take a long time on a home directory with a million files in it.
* Alternatively, even though Watchman can work with `$HOME`, it hasn't scanned it yet, and so it takes about as long as the `find` scanner would have.

For the latter case, nothing can make this fast, short of refusing to run on `$HOME` like you suggest. For the former, I am not sure if `g:CommandTMaxFiles` will at least allow you to abort scanning after some reasonable number of files (there is code in there to `break` on hitting the limit, but depending on how the output of `find` is getting buffered, there might be a lag before the `break` gets hit).

I think an acceptable workaround would be to either implement a whitelist (ie. Command-T would only run on directories with a marker file inside them, like `.git` etc) or a blacklist (ie. you could just tell it to always bail for `$HOME` or any other directory you mistakenly open it in). Note here that what "run"/"bail" mean here could depend: maybe you want to literally fail, or maybe you want to fall back to the "ruby" scanner with a low `g:CommandTMaxFiles` limit, or maybe something else...

Best of all, however, would be to do the scanning out of process and make it interruptable, so that you would have the option of either waiting for the scan to finish if you really wanted to, or effectively `Control-C`-ing it.

**Comment by trotzig** [comment]
Thanks! Your response made me look closer at watchman configuration options, and this combination did the trick: 

```json
// /etc/watchman.json
{
  "root_files": [".git"],
  "enforce_root_files": true
}
```

I had to add that to `/etc/watchman.json`. For some reason, having that in a local `~/.watchmanconfig` file didn't work. 

With this config, Command-T will fall back to the ruby scanner, and warn at some point that the maximum file limit has been reached. That's much better than freezing. :)
