### ISSUE TITLE
Command-T should open a file the current split

### ISSUE THREAD

**Issue by dylan-chong** [wincent/command-t#269]
Currently the file will open in the main split.

To replicate the undesired behaviour:

1. Open vim
2. Open another split (so you have 2 splits)
3. Move the cursor the new split
4. Trigger Command-T and open any file

This will result in the file being opened in the main split. Instead, it should open in the split that the cursor was in just before opening Command-T

**Comment by wincent** [comment]
Can't repro this. Have you tried the following?

- Set `'spitbelow'` and `'splitright'`?
- Set `'switchbuf'` to `usetab`?
- Using a `GotoOrOpen` function like the one mentioned in the docs?
- Running the latest `next` branch (which is ahead of master, and [bakes in](https://github.com/wincent/command-t/commit/5c99c0eaac28f0e4231d2b3241dba796ca097f03) the `GotoOrOpen` behavior by default).

I'm going to close this due to the inability to repro, but feel free to comment back if the above possible solutions don't help you.
