### ISSUE TITLE
Sometimes not a wrong file is opened in command-t

### ISSUE THREAD

**Issue by application-developer-DA** [wincent/command-t#295]
Seems like I found a bug. I've just updated to the latest version (I use Vundle for plugins in vim) and the bug is still there.

I have a directory with the following tree structure:
```
daniel@Lap-Daniel:~/test_vim$ tree
.
├── capturer.rs
└── win32
    └── capturer.rs
```

I open `vim` and run `:CommandT`, then I select `win32/capturer.rs` from the list, the proper file is loaded in my current buffer. Then I run `:CommandT` and select `capturer.rs` from the list, but still `win32/capturer.rs` is opened instead of `capturer.rs`.

What interesting is, if I try to open them in a different order (first `capturer.rs`, then `win32/capturer.rs`) the bug is not triggered. But when I load `win32/capturer.rs` first, every subsequent attempt to open `capturer.rs` loads `win32/capturer.rs`.

**Comment by wincent** [comment]
Thanks for the report!

This is happening because of some cleverness in [the `commandt#GotoOrOpen` function](https://github.com/wincent/command-t/blob/fd5e17f3ddb44edb41e090f8fede6b2e38592f0e/autoload/commandt.vim#L159-L172). If we add some `unsilent echomsg` logging to this function:

```
function! commandt#GotoOrOpen(command_and_args) abort
  let l:command_and_args = split(a:command_and_args, '\v^\w+ \zs')
  let l:command = l:command_and_args[0]
  let l:file = l:command_and_args[1]

  unsilent echomsg 'checking '.l:file
  " bufwinnr() doesn't see windows in other tabs, meaning we open them again
  " instead of switching to the other tab; but bufexists() sees hidden
  " buffers, and if we try to open one of those, we get an unwanted split.
  if bufwinnr(l:file) != -1 || (bufexists(l:file) && !s:BufHidden(l:file))
    unsilent echomsg 'using sbuffer '.l:file
    execute 'sbuffer ' . l:file
  else
    unsilent echomsg 'using '.l:command.' '.l:file
    execute l:command . l:file
  endif
endfunction
```

And then run your repro recipe (open "win32/capturer.rs" then "capturer.rs"), `:messages` shows this log:

```
checking win32/capturer.rs
using e  win32/capturer.rs
checking capturer.rs
using sbuffer capturer.rs
```

So the first file is opened with `:edit` and the second with `:sbuffer`. `:sbuffer` is what allows us to re-open existing stuff without opening an existing copy, but as you can see here it is actually doing the opposite of what we want. This will only happen for files at the top level. When we open the files in the opposite order we see:

```
checking capturer.rs
using e  capturer.rs
checking win32/capturer.rs
using e  win32/capturer.rs
```

And `:e` is used both times. It should be possible to make `commandt#GotoOrOpen` ever so slightly smarter to avoid this issue. I'll play around with it and see what I can cook up.

**Comment by wincent** [comment]
So I've pushed a potential fix. Hopefully haven't broken anything else with it. Let me know if you run into any issues. Thanks once again for the report.
