### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by TahaMagdy** [wincent/command-t#355]
Can I select files that I open frequently and put them in a CommandT list; so that I open the CommandT list to open a file from them?! 

I don't mean a list of the most recent opened file, I mean that I specifically select the files to be in that list.

How can I do that?!

**Comment by wincent** [comment]
Nothing's implemented currently but I can see two relatively straightforward ways to do this:

- One would be to implement a "favorites" or "bookmarks" scanner & finder that allowed you to specify a list of favorites somewhere (either in your `.vimrc` or via a config file).
- Another would be to make a variant of the most-recently-used-buffer scanner/finder: this would be most-frequently-used files, and would persist across restarts.

Finally, I think a variant on that last one — but not easy to implement — would be to allow frequently-used files to be boosted higher in results listings.

**Comment by TahaMagdy** [comment]
The fist solution is the one I think. To make "Bookmarks". How can I do that please?
You may tell me how the CommandT list read the array of files? And I'll implement it.

**Comment by wincent** [comment]
- The "scanners" are responsible for getting a list of files; there are multiple examples in [this "scanners" directory](https://github.com/wincent/command-t/tree/master/ruby/command-t/lib/command-t/scanner).
- The "finders" are responsible for managing a scanner and providing logic for "opening" whatever the user accepts: examples are in [the "finders" directory](https://github.com/wincent/command-t/tree/master/ruby/command-t/lib/command-t/finder).

In your case, you'd create a new scanner to read the list of "bookmarks", and your finder would be very simple because all it has to do is instantiate the scanner; as you're dealing with files, just letting [the superclass `open_selection` implementation](https://github.com/wincent/command-t/blob/57e112c12c99185e062a4330896cfaf422d1ea64/ruby/command-t/lib/command-t/finder.rb#L42-L44) handle the actual opening should be fine, as long as you're dealing with absolute paths.

Finally, you have to wire things up so that [the controller](https://github.com/wincent/command-t/blob/master/ruby/command-t/lib/command-t/controller.rb) knows about your finder, and the user has [a Vim command](https://github.com/wincent/command-t/blob/master/autoload/commandt/mirkwood.vim) that they can invoke to access your finder.

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
