### ISSUE TITLE
Support for floating window?

### ISSUE THREAD

**Issue by arumoy-shome** [wincent/command-t#366]
My apologies if a solution/method for this already exists (from a bit of googling around and reading the docs, I did not find any help on the matter). Now that floating windows are a thing in vim as well, will command-t also support this feature?

Many thanks for the awesome work on this and your other plugins!  (I use them all 😄)

**Comment by wincent** [comment]
No plans to support it, but that's only because I haven't thought about it at all; it might actually be a great idea.

Main thing is though people expect the plug-in to keep working on older versions of Vim, and I don't want to carry around a lot of baggage with compatibility code (because I don't have a lot of time to work on this, I need to keep things slim), so I'd be inclined to do this kind of thing on the `next` branch and drop the old implementation. Sadly, it is hard to make any aggressive changes ever on the `master` branch because people just point their installations at that branch and pay no attention to semver breaking changes when the major version number goes up.

**Comment by arumoy-shome** [comment]
Thank you for the response, closing this issue. 👍
