### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by fi0** [wincent/command-t#372]
My guess is P in Ctrl-P stands for command Palette.
What does T in command-t stand for? Is it Tab? Tag? or Tool?

**Comment by wincent** [comment]
It's detailed [in the first paragraph of the docs](https://github.com/wincent/command-t/blob/ea7a889bda2849ba87fc12053bf6dd14467d7b72/doc/command-t.txt#L26-L29):

> It's named "Command-T" because it is inspired by the "Go to File" window bound to Command-T in TextMate.

Command-T predates ctrlp by almost a year and a half:

- [First commit](https://github.com/wincent/command-t/commit/8378eeb94f1c7e5656696fc6c52d8aa69831f809) in Command-T repo: Fri Feb 26 20:25:17 2010 +0100
- [First commit](https://github.com/kien/ctrlp.vim/commit/224b504c3dcc892cab270b946a8dbbf6916ca149) in ctrlp.vim repo: Tue Jun 21 08:21:58 2011 +0700

So I guess he/she just copied the naming pattern, picked a different key, and that's why it's called as it is. I have no idea if the "P" stands for anything.
