### ISSUE TITLE
Is it possible to run gvim 8.2, win 10 and still use command-t

### ISSUE THREAD

**Issue by steinbitglis** [wincent/command-t#382]
I have tried a lot of different things, and I have managed to run _ruby extconf.rb_ and _make_ successfully, but I'm getting this message when I run ':CommandT'

> command-t.vim could not load the C extension
> Please see INSTALLATION and TROUBLE-SHOOTING in the help
> Vim Ruby version: 2.4.10-p364
> Expected version: 1.9.2-p290
> For more information type:   :help command-t

I've used ruby 2.4.10 to compile the thing with no error, so I don't understand why it still wants to be 1.9.2-p290.

**Comment by steinbitglis** [comment]
What I did to compile was launch "C:\Ruby24\msys32\mingw32.exe" and export PATH=/c/Ruby24/bin:/c/Ruby24/bin/ruby_builtin_dlls:$PATH
Then I went to  /c/Users/Steinbitglis/vimfiles/bundle/command-t/ruby/command-t/ext/command-t   and ran  _ruby extconf.rb_  and _make_

**Comment by steinbitglis** [comment]
The reason for the message regarding 1.9.2-p290 was that i had an old install of command-t in another folder.
When I removed that, I managed to run CommandT, but it crashed for other reasons. Probably ruby 2.4 isn't compatible. I guess, that the original question stands, even though I have now rolled back to the old 1.9.2-p290 compiled version, since that's working.

**Comment by wincent** [comment]
> Probably ruby 2.4 isn't compatible.

In principle, there's no reason why v2.4 shouldn't work. I'm using different versions of Ruby on different machines (v2.6.3-p62 on the machine I'm on right now, albeit a macOS machine); there's nothing special about that version though, as I've used older and newer Ruby versions in different places.

One thing to bear in mind is it's always worth doing a `make clean` as part of any of these troubleshooting sessions, because there's always a chance that you end up not testing the artifact that you think you're testing (as you discovered with the rogue version you found in another folder).

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
