### ISSUE TITLE
Optionally ignore symlinks

### ISSUE THREAD

**Issue by blueyed** [wincent/command-t#66]
I would like to ignore symlinks with Command-T (except for the one given, i.e. `:CommandT /path/to/symlink` would resolve the link, but links therein would be ignored).

I have found that there is a new file scanner (`:let g:CommandTFileScanner='find'`), where instead of the `-L` option `-H` would be used.

The ruby scanner would need to skip them here: https://github.com/wincent/Command-T/blob/master/ruby/command-t/scanner/file_scanner/ruby_file_scanner.rb#L66

**Comment by cl20vv** [comment]
I've got a project which has as many as 12000 files, but when add new files to the project, i couldn't search the new files(foo) anyway in the root directory, but i could search files in it's own directory. I've also tried let g:CommandTMaxFiles=40000, which count is much lager then 12000, but it was still not work. And then i deleted folder one by one, tried to find out which folder interrupt the search. happenly when I delete the symlink to linux kernel source, everything goes well. I found there are 70325 files in linux-source directory. and my new added files are behind the the source code, so that's why i couldn't find it.

any new added files behind linux-26, would not be found, when g:CommandTMaxFiles is not large enough.

I also need to ignore the symlinks. thks.

```` bash
# find
......
./Makefile
./config.h
./.gitignore
./.vim-bookmarks
./Bookmark.vim
./mygen
./mygen/mygen.sh
./linux-26
./foo
./foo/0
./foo/1
./foo/2
````

**Comment by wincent** [comment]
Yeah, we can/should probably do this.

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
